version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - sonarqube
    environment:
      - SONARQUBE_HOST=http://localhost:9000  # Reference SonarQube in Compose network
    networks:
      - sonar-network

  sonarqube:
    image: sonarqube:latest
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonar-db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    ports:
      - "9000:9000"
    networks:
      - sonar-network
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
    restart: always

  sonarqube-db:
    image: postgres:13
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    networks:
      - sonar-network
    volumes:
      - sonar-db-data:/var/lib/postgresql/data
    restart: always

networks:
  sonar-network:
    driver: bridge

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonar-db-data:
